# Generated by Django 3.0.10 on 2020-09-27 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20200925_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='same_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_street_address', models.CharField(max_length=200)),
                ('billing_apartment_address', models.CharField(blank=True, max_length=100)),
                ('billing_postal_code', models.CharField(max_length=30)),
                ('billing_city', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
