# Generated by Django 3.0.10 on 2020-10-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201022_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
