# Generated by Django 3.0.10 on 2020-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='title',
            field=models.CharField(default=False, max_length=250),
        ),
    ]
