# Generated by Django 3.0.10 on 2020-09-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='same_billing',
            field=models.BooleanField(default=False),
        ),
    ]
