# Generated by Django 3.0.10 on 2020-10-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201004_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='same_billing',
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_street_address', models.CharField(max_length=200)),
                ('billing_apartment_address', models.CharField(blank=True, max_length=100)),
                ('billing_postal_code', models.CharField(max_length=30)),
                ('billing_city', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='orders.Order')),
            ],
        ),
    ]
